security:

    # Define standard users
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: ryanpass
                        roles: 'ROLE_USER'
                    admin:
                        password: kitten
                        roles: 'ROLE_ADMIN'

    # User passwords are "encoded" as plaintext
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # No security needed for assets
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Don't allow anonymous access, and use HTTP_BASIC as auth mechanism
        main:
            anonymous: false
            autologin: true
            http_basic: ~
